In [197]:
#importation module pandas
import pandas as pd

In [198]:
#Importer le csv dans un DataFrame pandas
#compression de gzip directement et lecture de csv
full_csv = pd.read_csv('https://cadastre.data.gouv.fr/data/etalab-dvf/latest/csv/2020/full.csv.gz', compression='gzip',  header=0, sep=',', quotechar='"')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10,12,17,18,20,22,35,36) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [199]:
full_csv.head()

  id_mutation date_mutation  ...  longitude   latitude
0      2020-1    2020-01-07  ...   5.323522  46.171899
1      2020-2    2020-01-07  ...   5.226197  46.184538
2      2020-3    2020-01-14  ...        NaN        NaN
3      2020-3    2020-01-14  ...        NaN        NaN
4      2020-4    2020-01-22  ...   5.219902  46.196484

[5 rows x 40 columns]

In [200]:
#le type de document
type(full_csv)

pandas.core.frame.DataFrame

In [201]:
#taille de ficheir
full_csv.shape

(827105, 40)

In [202]:
#ajouter une colonnne contenent vore nom
full_csv.insert(0, 'NOM_CANDIDAT', "BAGHROSSE-Rachid")
#full_csv["NOM_CANDIDAT"]="BAGHROSSE-Rachid"

In [203]:
full_csv['NOM_CANDIDAT']

0         BAGHROSSE-Rachid
1         BAGHROSSE-Rachid
2         BAGHROSSE-Rachid
3         BAGHROSSE-Rachid
4         BAGHROSSE-Rachid
                ...
827100    BAGHROSSE-Rachid
827101    BAGHROSSE-Rachid
827102    BAGHROSSE-Rachid
827103    BAGHROSSE-Rachid
827104    BAGHROSSE-Rachid
Name: NOM_CANDIDAT, Length: 827105, dtype: object

In [204]:
#Ajouter une colonne portant le nom « adresse_string »
full_csv['code_postal'] = full_csv['code_postal'].astype(str)
pays= 'FRANCE'
full_csv["adresse_string"] = (full_csv['adresse_code_voie'] + ' ' + full_csv['adresse_nom_voie'] + ', ' + full_csv['nom_commune'] + ', ' + full_csv['code_postal'] + ', '+ pays)

In [205]:
print(full_csv.adresse_string)

0                  B063 FORTUNAT, Ceyzériat, 1250.0, FRANCE
1         0064 RUE DE LA CHARTREUSE, Péronnas, 1960.0, F...
2                  B112 VACAGNOLE, Attignat, 1340.0, FRANCE
3                  B112 VACAGNOLE, Attignat, 1340.0, FRANCE
4           3340 RUE REYER, Bourg-en-Bresse, 1000.0, FRANCE
                                ...
827100    6513 RUE MONTMARTRE, Paris 2e Arrondissement, ...
827101    8073 RUE REAUMUR, Paris 2e Arrondissement, 750...
827102    1797 RUE CHARLEMAGNE, Paris 4e Arrondissement,...
827103    1669 RUE CHABANAIS, Paris 2e Arrondissement, 7...
827104    8659 RUE SAINT-JOSEPH, Paris 2e Arrondissement...
Name: adresse_string, Length: 827105, dtype: object

In [24]:
# la suppression des lignes ayant l'un de ces attributs null
full_csv.dropna(subset=['longitude', 'latitude'])

            NOM_CANDIDAT  ...                                     adresse_string
0       BAGHROSSE-Rachid  ...  B063 FORTUNAT, Ceyzériat, 0          1250.0\n1...
1       BAGHROSSE-Rachid  ...  0064 RUE DE LA CHARTREUSE, Péronnas, 0        ...
4       BAGHROSSE-Rachid  ...  3340 RUE REYER, Bourg-en-Bresse, 0          12...
5       BAGHROSSE-Rachid  ...  B025 LES GUYOTS, Montrevel-en-Bresse, 0       ...
6       BAGHROSSE-Rachid  ...  B013 CUET, Montrevel-en-Bresse, 0          125...
...                  ...  ...                                                ...
827100  BAGHROSSE-Rachid  ...  6513 RUE MONTMARTRE, Paris 2e Arrondissement, ...
827101  BAGHROSSE-Rachid  ...  8073 RUE REAUMUR, Paris 2e Arrondissement, 0  ...
827102  BAGHROSSE-Rachid  ...  1797 RUE CHARLEMAGNE, Paris 4e Arrondissement,...
827103  BAGHROSSE-Rachid  ...  1669 RUE CHABANAIS, Paris 2e Arrondissement, 0...
827104  BAGHROSSE-Rachid  ...  8659 RUE SAINT-JOSEPH, Paris 2e Arrondissement...

[780131 rows x 42 columns]

In [25]:
#trie de resultat par date pour récupérer les plus récents enregistrements
trie=full_csv.sort_values(by='date_mutation')
trie.tail(500)

            NOM_CANDIDAT  ...                                     adresse_string
55739   BAGHROSSE-Rachid  ...  0690 RUE DES FOSSES, Nogent-sur-Seine, 0      ...
55738   BAGHROSSE-Rachid  ...  0690 RUE DES FOSSES, Nogent-sur-Seine, 0      ...
55737   BAGHROSSE-Rachid  ...  0690 RUE DES FOSSES, Nogent-sur-Seine, 0      ...
615123  BAGHROSSE-Rachid  ...  0140 BD CARNOT, Hardricourt, 0          1250.0...
615124  BAGHROSSE-Rachid  ...  0038 RUE DE LA BATELLERIE, Carrières-sous-Pois...
...                  ...  ...                                                ...
55942   BAGHROSSE-Rachid  ...  2880 RUE JEANNETTE, Troyes, 0          1250.0\...
55941   BAGHROSSE-Rachid  ...  2880 RUE JEANNETTE, Troyes, 0          1250.0\...
55940   BAGHROSSE-Rachid  ...  2880 RUE JEANNETTE, Troyes, 0          1250.0\...
564068  BAGHROSSE-Rachid  ...  0742 RUE DE LA NOBLE EPINE, Bois-Guillaume, 0 ...
709439  BAGHROSSE-Rachid  ...  B037 LE PAUMIER, Crain, 0          1250.0\n1  ...

[500 rows x 42 columns]